swagger: "2.0"
info:
  description: "This project provides a platform to interact via REST APIs with Oracle Autonomous Transaction Procesing Database (ATP) to create and redeem gifts and crosswords."
  version: "2.1.0"
  title: "APIs 4 Gifts Demo"
  #termsOfService: "http://apismadeeasy.cloud/terms"
  contact:
    email: "carlos.rodriguez.iturria@oracle.com"
  #license:
  #  name: "Apache 2.0"
  #  url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/"
host: "localhost:3000"
#basePath: "/nf/gifts"
#host: "apipdev.oracleau.cloud"
tags:
- name: "Games"
  description: "Games to be played"
  externalDocs:
    description: "Find out more"
    url: "http://apismadeeasy.cloud"
- name: "GameObjects"
  description: "Game object interactions, e.g. Augmented Reality."
  externalDocs:
    description: "Find out more"
    url: "http://apismadeeasy.cloud"
- name: "GamePlayerInteractions"
  description: "This is the interaction of Players interacting with a particular Game."
  externalDocs:
    description: "Find out more"
    url: "http://apismadeeasy.cloud"
- name: "GamePlayers"
  description: "Players to be engaging into a game."
  externalDocs:
    description: "Find out more"
    url: "http://apismadeeasy.cloud"    
schemes:
#- "https"
- "http"
security:
  - X-MyAPI-Key: []
paths:
  /games:
    get:
      tags:
      - "Games"
      summary: "Finds all records information."
      description: "Gets all records information"
      operationId: "getGames"
      produces: 
        - "application/json"
      responses:
        200:
          description: "Returns records data."
          schema:
            properties:
              games:
                type: "array"
                items:
                  $ref: "#/definitions/GamesResponse"
          examples:
            application/json:
              games:
                - gid: 12345
                  name: koala
                - gid: 12346
                  name: kangaroo
  /games/{gid}:
    get:
      tags:
      - "Games"
      summary: "Finds records information."
      description: "Gets all records information or by Id"
      operationId: "getGamesById"
      produces: 
        - "application/json"
      parameters:
      - name: "gid"
        in: "path"
        description: "Field used to filter the record to be returned."
        required: true
        type: "string"
        x-example: '12345'
      responses:
        200:
          description: "Returns records data."
          schema:
            properties:
              game:
                $ref: "#/definitions/GamesResponse"
          examples:
            application/json:
              game:
                gid: 12345
                name: koala

  /gos:
    get:
      tags:
      - "GameObjects"
      summary: "Finds all records information."
      description: "Gets all records information"
      operationId: "getGameObjects"
      produces: 
        - "application/json"
      responses:
        200:
          description: "Returns records data."
          schema:
            properties:
              gameObjects:
                type: "array"
                items:
                  $ref: "#/definitions/GameObjectsResponse"
          examples:
            application/json:
              gameObjects:
                - goid: 12345
                  name: koala
                  description: Try to play with this amazing game.
                  latitude: -37.835311
                  longtitude: 144.9725336
                  altitude: 31
                  imageURL: https://i.4pcdn.org/x/1508011708146.png
                  type: ar
                  gid: 12345
                - goid: 12346
                  name: bear
                  description: Try to play with this amazing game.
                  latitude: -37.835311
                  longtitude: 144.9725336
                  altitude: 31
                  imageURL: https://i.4pcdn.org/x/1508011708146.png
                  type: reveal
                  gid: 12345

  /gos/{goid}:
    get:
      tags:
      - "GameObjects"
      summary: "Finds records information."
      description: "Gets all records information or by Id"
      operationId: "getGameObjectsById"
      produces: 
        - "application/json"
      parameters:
      - name: "goid"
        in: "path"
        description: "Field used to filter the record to be returned."
        required: true
        type: "string"
        x-example: '12345'
      responses:
        200:
          description: "Returns records data."
          schema:
            properties:
              gameObject:
                $ref: "#/definitions/GameObjectsResponse"
          examples:
            application/json:
              gameObject:
                goid: 12346
                name: bear
                description: Try to play with this amazing game.
                latitude: -37.835311
                longtitude: 144.9725336
                altitude: 31
                imageURL: https://i.4pcdn.org/x/1508011708146.png
                type: reveal
                gid: 12345


  /players:
    get:
      tags:
      - "GamePlayers"
      summary: "Finds all records information."
      description: "Gets all records information"
      operationId: "getGamePlayers"
      produces: 
        - "application/json"
      responses:
        200:
          description: "Returns records data."
          schema:
            properties:
              players:
                type: "array"
                items:
                  $ref: "#/definitions/GamePlayersResponse"
          examples:
            application/json:
              players:
                - gpid: 12345
                  memberId: 54321
                  name: Daniel Jonas
                - gpid: 12346
                  memberId: 34567
                  name: Brenton Lee

  /players/{gpid}:
    get:
      tags:
      - "GamePlayers"
      summary: "Finds records information."
      description: "Gets all records information or by Id"
      operationId: "getGamePlayersById"
      produces: 
        - "application/json"
      parameters:
      - name: "gpid"
        in: "path"
        description: "Field used to filter the record to be returned."
        required: true
        type: "string"
        x-example: '12345'
      responses:
        200:
          description: "Returns records data."
          schema:
            properties:
              player:
                $ref: "#/definitions/GamePlayersResponse"
          examples:
            application/json:
              player:
                gpid: 12346
                memberId: 34567
                name: Brenton Lee     

  /gpis:
    get:
      tags:
      - "GamePlayerInteractions"
      summary: "Finds records information."
      description: "Gets all records information by using optional filters."
      operationId: "getGamePlayerInteractions"
      produces: 
        - "application/json"
      responses:
        200:
          description: "Returns records data."
          schema:
            properties:
              GamePlayerInteractions:
                type: "array"
                items:
                  $ref: "#/definitions/GamePlayerInteractionsResponse"
          examples:
            application/json:
              GamePlayerInteractions:
                - goid: 12345
                  gpid: 54321
                  gpiLat: -37.835311
                  gpiLong: 144.9725336
                  gpiDate: 2018-12-21T00:00:00.000Z
                  gpiResult: Accepted
                - goid: 12346
                  gpid: 54322
                  gpiLat: -37.835311
                  gpiLong: 144.9725336
                  gpiDate: 2018-12-21T00:00:00.000Z
                  gpiResult: Accepted
              
    post:
      tags:
      - "GamePlayerInteractions"
      summary: "Creates new Records."
      description: "Returns the just inserted record(s)."
      operationId: "postGamePlayerInteractions"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Array of records that need to be added."
        required: true
        schema:
            properties:
              GamePlayerInteractions:
                type: "array"
                items:
                  $ref: "#/definitions/GamePlayerInteractionsRequest"
      responses:
        200:
          description: "Returns the just created record(s)."
          schema:
            properties:
              GamePlayerInteractions:
                type: "array"
                items:
                  $ref: '#/definitions/GamePlayerInteractionsResponse'
          examples:
            application/json:
              GamePlayerInteractions:
                - goid: 12345
                  gpid: 54321
                  gpiLat: -37.835311
                  gpiLong: 144.9725336
                  gpiDate: "2018-12-21T00:00:00.000Z"
                  gpiResult: Accepted
                - goid: 12346
                  gpid: 54322
                  gpiLat: -37.835311
                  gpiLong: 144.9725336
                  gpiDate: "2018-12-21T00:00:00.000Z"
                  gpiResult: Accepted

  /gpis/{gpis_id}:
    put:
      tags:
      - "GamePlayerInteractions"
      summary: "Update record information from this instance."
      description: "Returns updated value."
      operationId: "putGamePlayerInteractionsById"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "gpis_id"
        in: "path"
        description: "Record id to filtewr on"
        required: true
        type: "string"
        x-example: '12345'
      - in: "body"
        name: "body"
        description: "Full details of record to be updated with."
        required: true
        schema:
          properties:
            GamePlayerInteraction:
              $ref: "#/definitions/GamePlayerInteractionsRequest"
      responses:
        200:
          description: "Returns acknowledgment message."
          schema:
            properties:
              GamePlayerInteraction:
                $ref: '#/definitions/GamePlayerInteractionsRequest'  
            
            
securityDefinitions:
  X-MyAPI-Key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  GamesResponse:
    type: "object"
    required:
    - "gid"
    - "name"
    properties:
      gid:
        type: "number"
        example: 12345
      name:
        type: "string"
        example: "koala"

  GameObjectsResponse:
    type: "object"
    required:
    - "goid"
    - "name"
    - "description"
    - "latitude"
    - "longtitude"
    - "altitude"
    - "imageURL"
    - "type"
    - "gid"
    properties:
      goid:
        type: "number"
        example: 12346
      name:
        type: "string"
        example: "bear"
      description:
        type: "string"
        example: "Try to play with this amazing game."
      latitude:
        type: "number"
        example: -37.835311
      longtitude:
        type: "number"
        example: 144.9725336
      altitude:
        type: "number"
        example: 31
      imageURL:
        type: "string"
        example: "https://i.4pcdn.org/x/1508011708146.png"
      type:
        type: "string"
        example: "reveal"
      gid:
        type: "number"
        example: 12345

  GamePlayersResponse:
    type: "object"
    required:
    - "gpid"
    - "memberId"
    - "name"
    properties:
      gpid:
        type: "number"
        example: 12345
      memberId:
        type: "number"
        example: 54321
      name:
        type: "string"
        example: "Daniel Jonas"      


  GamePlayerInteractionsRequest:
    type: "object"
    required:
    - "goid"
    - "gpid"
    - "gpiLat"
    - "gpiLong"
    - "gpiResult"
    properties:
      goid:
        type: "number"
        example: 12346
      gpid:
        type: "number"
        example: 54322
      gpiLat:
        type: "number"
        example: -37.835311
      gpiLong:
        type: "number"
        example: 144.9725336
      gpiResult:
        type: "string"
        example: "Acepted"

  GamePlayerInteractionsResponse:
    type: "object"
    required:
    - "goid"
    - "gpid"
    - "gpiLat"
    - "gpiLong"
    - "gpiDate"
    - "gpiResult"
    properties:
      goid:
        type: "number"
        example: 12346
      gpid:
        type: "number"
        example: 54322
      gpiLat:
        type: "number"
        example: -37.835311
      gpiLong:
        type: "number"
        example: 144.9725336
      gpiDate:
        type: "string"
        example: "2018-12-21T00:00:00.000Z"
      gpiResult:
        type: "string"
        example: "Acepted"

externalDocs:
  description: "Find out more about our APIs"
  url: "http://apisMadeEasy.cloud"