DROP TABLE GAMES CASCADE CONSTRAINTS PURGE;
DROP TABLE GAME_OBJECTS CASCADE CONSTRAINTS PURGE;
DROP TABLE GAME_PLAYER_INTERACTIONS CASCADE CONSTRAINTS PURGE;
DROP TABLE GAME_PLAYERS CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE GAMES_SEQ;
DROP SEQUENCE GAME_OBJECTS_SEQ;
DROP SEQUENCE GAME_PLAYERS_SEQ;
DROP SEQUENCE GAME_PLAYER_INTERACTIONS_SEQ;

--------------------------------------------------------
--  DDL for Sequence GAME_OBJECTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAME_OBJECTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   
--------------------------------------------------------
--  DDL for Sequence GAME_PLAYERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAME_PLAYERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--------------------------------------------------------
--  DDL for Sequence GAMES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAMES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  
--------------------------------------------------------
--  DDL for Sequence GAME_PLAYER_INTERACTIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAME_PLAYER_INTERACTIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   
CREATE TABLE "GAMES" (
    "GAME_ID"     NUMBER(3,0)
        NOT NULL ENABLE,
    "GAME_NAME"   VARCHAR2(26 BYTE)
        NOT NULL ENABLE,
    CONSTRAINT "GAMES_PK" PRIMARY KEY ( "GAME_ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "DATA"
    ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
TABLESPACE "DATA";

CREATE OR REPLACE EDITIONABLE TRIGGER "GAMES_TRG" BEFORE
    INSERT ON games
    FOR EACH ROW
BEGIN
    << column_sequences >> BEGIN
        IF
            inserting AND :new.game_id IS NULL
        THEN
            SELECT
                games_seq.NEXTVAL
            INTO :new.game_id
            FROM
                sys.dual;

        END IF;
    END column_sequences;
END;
/

ALTER TRIGGER "GAMES_TRG" ENABLE;

CREATE TABLE "GAME_OBJECTS" (
    "GAME_OBJECT_ID"    NUMBER(38,0)
        NOT NULL ENABLE,
    "GAME_OBJECT"       VARCHAR2(26 BYTE)
        NOT NULL ENABLE,
    "OBJECT_TYPE"       VARCHAR2(26 BYTE)
        NOT NULL ENABLE,
    "OBJECT_LAT"        NUMBER(38,6)
        NOT NULL ENABLE,
    "OBJECT_LONG"       NUMBER(38,6)
        NOT NULL ENABLE,
    "OBJECT_ALTITUDE"   NUMBER(38,0)
        NOT NULL ENABLE,
    "OBJECT_URL"        VARCHAR2(128 BYTE)
        NOT NULL ENABLE,
    "GAME_ID"           NUMBER(38,0)
        NOT NULL ENABLE,
    "OBJECT_ADDRESS"    VARCHAR2(128 BYTE)
        NOT NULL ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
TABLESPACE "DATA";

CREATE OR REPLACE EDITIONABLE TRIGGER "GAME_OBJECTS_TRG" BEFORE
    INSERT ON game_objects
    FOR EACH ROW
BEGIN
    << column_sequences >> BEGIN
        IF
            inserting AND :new.game_object_id IS NULL
        THEN
            SELECT
                game_objects_seq.NEXTVAL
            INTO :new.game_object_id
            FROM
                sys.dual;

        END IF;
    END column_sequences;
END;
/

ALTER TRIGGER "GAME_OBJECTS_TRG" ENABLE;

CREATE TABLE "GAME_PLAYERS" (
    "PLAYER_ID"     NUMBER(38,0)
        NOT NULL ENABLE,
    "PLAYER_NAME"   VARCHAR2(26 BYTE)
        NOT NULL ENABLE,
    "MEMBER_ID"     NUMBER(38,0),
    CONSTRAINT "GAME_PLAYERS_PK" PRIMARY KEY ( "PLAYER_ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "DATA"
    ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
TABLESPACE "DATA";

CREATE OR REPLACE EDITIONABLE TRIGGER "GAME_PLAYERS_TRG" BEFORE
    INSERT ON game_players
    FOR EACH ROW
BEGIN
    << column_sequences >> BEGIN
        IF
            inserting AND :new.player_id IS NULL
        THEN
            SELECT
                game_players_seq.NEXTVAL
            INTO :new.player_id
            FROM
                sys.dual;

        END IF;
    END column_sequences;
END;
/

CREATE TABLE "GAME_PLAYER_INTERACTIONS" (
    "GPI_ID"           VARCHAR2(26 BYTE)
        NOT NULL ENABLE,
    "GAME_OBJECT_ID"   NUMBER(38,0)
        NOT NULL ENABLE,
    "PLAYER_ID"        NUMBER(38,0)
        NOT NULL ENABLE,
    "GPI_LAT"          NUMBER(38,4)
        NOT NULL ENABLE,
    "GPI_LONG"         NUMBER(38,4)
        NOT NULL ENABLE,
    "GPI_DATE"         DATE
        NOT NULL ENABLE,
    "GPI_RESULT"       VARCHAR2(26 BYTE)
        NOT NULL ENABLE,
    CONSTRAINT "GAME_PLAYER_INTERACTIONS_PK" PRIMARY KEY ( "GPI_ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "DATA"
    ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT
CELL_FLASH_CACHE DEFAULT )
TABLESPACE "DATA";

CREATE OR REPLACE EDITIONABLE TRIGGER "GAME_PLAYER_INTERACTIONS_TRG" BEFORE
    INSERT ON game_player_interactions
    FOR EACH ROW
BEGIN
    << column_sequences >> BEGIN
        IF
            inserting AND :new.gpi_id IS NULL
        THEN
            SELECT
                game_player_interactions_seq.NEXTVAL
            INTO :new.gpi_id
            FROM
                sys.dual;

        END IF;
    END column_sequences;
END;
/

ALTER TRIGGER "GAME_PLAYER_INTERACTIONS_TRG" ENABLE;

INSERT INTO GAMES (GAME_NAME) VALUES ('KOALA');
INSERT INTO GAMES (GAME_NAME) VALUES ('Christmas Pageant');
INSERT INTO GAMES (GAME_NAME) VALUES ('Easter 2019');
COMMIT;
INSERT INTO GAME_PLAYERS ( PLAYER_NAME, MEMBER_ID) VALUES ('Carlos',NULL);
INSERT INTO GAME_PLAYERS ( PLAYER_NAME, MEMBER_ID) VALUES ('Dave',12345);
INSERT INTO GAME_PLAYERS ( PLAYER_NAME, MEMBER_ID) VALUES ('Stuart',NULL);
INSERT INTO GAME_PLAYERS ( PLAYER_NAME, MEMBER_ID) VALUES ('Vijay',NULL);
INSERT INTO GAME_PLAYERS ( PLAYER_NAME, MEMBER_ID) VALUES ('Franco',67891);
COMMIT;
INSERT INTO GAME_OBJECTS (GAME_OBJECT, OBJECT_TYPE, OBJECT_LAT, OBJECT_LONG, OBJECT_ALTITUDE, OBJECT_URL, GAME_ID, OBJECT_ADDRESS) 
VALUES ('Koala','Revealed',-34.923320, 138.602140, 10, 'http://www.np.com/koala.jpg',1, '52 Gawler Place, Adelaide, South Australia');
INSERT INTO GAME_OBJECTS (GAME_OBJECT, OBJECT_TYPE, OBJECT_LAT, OBJECT_LONG, OBJECT_ALTITUDE, OBJECT_URL, GAME_ID, OBJECT_ADDRESS) 
VALUES ('Santa','Static',-34.923320, 138.602140, 10, 'http://www.np.com/christmas.jpg',2,'52 Gawler Place, Adelaide, South Australia');
INSERT INTO GAME_OBJECTS (GAME_OBJECT, OBJECT_TYPE, OBJECT_LAT, OBJECT_LONG, OBJECT_ALTITUDE, OBJECT_URL, GAME_ID, OBJECT_ADDRESS) 
VALUES ('Easter Bunny','AR',-34.923320, 138.602140, 10, 'http://www.np.com/bunny.jpg',3, '52 Gawler Place, Adelaide, South Australia');
COMMIT;
INSERT INTO GAME_PLAYER_INTERACTIONS (GAME_OBJECT_ID,PLAYER_ID,GPI_LAT,GPI_LONG, GPI_DATE, GPI_RESULT)
VALUES(1,1,-34.924720,138.600830,'21-DEC-2018','ACCEPTED');
INSERT INTO GAME_PLAYER_INTERACTIONS (GAME_OBJECT_ID,PLAYER_ID,GPI_LAT,GPI_LONG, GPI_DATE, GPI_RESULT)
VALUES(2,2,-34.924720,138.600830,'12-DEC-2018','ACCEPTED');
INSERT INTO GAME_PLAYER_INTERACTIONS (GAME_OBJECT_ID,PLAYER_ID,GPI_LAT,GPI_LONG, GPI_DATE, GPI_RESULT)
VALUES(3,3,-34.924720,138.600830,'18-DEC-2018','ACCEPTED');
COMMIT;
